version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: splp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - splp-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: splp-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      # Performance tuning
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - splp-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  cassandra:
    image: cassandra:4.1
    container_name: splp-cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      CASSANDRA_CLUSTER_NAME: splp-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 256
      # Memory settings
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M
      # Performance tuning
      CASSANDRA_CONCURRENT_READS: 32
      CASSANDRA_CONCURRENT_WRITES: 32
      CASSANDRA_CONCURRENT_COUNTER_WRITES: 32
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./src/test/resources/cassandra-init.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - splp-network
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Optional: Kafka UI for development and debugging
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: splp-kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: splp-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - splp-network
    profiles:
      - dev

  # Optional: Cassandra Web UI for development
  cassandra-web:
    image: ipushc/cassandra-web:latest
    container_name: splp-cassandra-web
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    networks:
      - splp-network
    profiles:
      - dev

volumes:
  kafka_data:
    driver: local
  cassandra_data:
    driver: local

networks:
  splp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16